version: "3.9"
services:
  rallyhost:
    build: ../test_scripts/debian/Dockerfile
    image: couchbase/debian
    hostname: 'clusterhost'
    tty: true
    ports: 
      - "8080:8091"
    networks:
      - cb-net-debian
    container_name: debian-clusterhost
    command: --version 6.6.1 -u couchbase -p foo123! -ch clusterhost -d -os DEBIAN -r
    privileged: true
  nodeone:
    image: couchbase/debian
    hostname: 'node_one'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-debian
    ports: 
      - "8081:8091"
    container_name: debian-node-one
    command: --version 6.6.1 -u couchbase -p foo123! -ch clusterhost -d -os DEBIAN -r
    privileged: true
  nodetwo:
    image: couchbase/debian
    hostname: 'node_two'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-debian
    ports: 
      - "8082:8091"
    container_name: debian-node-two
    command: --version 6.6.1 -u couchbase -p foo123! -ch clusterhost -d -os DEBIAN -r
    privileged: true
networks:
  cb-net-debian: