version: "3.3"
services:
  rallyhost:
    build:
      context: ../
      dockerfile: ./test_scripts/ubuntu/Dockerfile
    image: couchbase/ubuntu
    hostname: 'clusterhost'
    tty: true
    ports: 
      - "8091:8091"
    networks:
      - cb-net-ubuntu
    container_name: ubuntu-clusterhost
    command: --version 7.0.2 -u couchbase -p foo123! -ch clusterhost -d -os UBUNTU -r -w 3
    privileged: true
  nodeone:
    image: couchbase/ubuntu
    hostname: 'node_one'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "9091:8091"
    container_name: ubuntu-node-one
    command: --version 7.0.2 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -r
    privileged: true
  nodetwo:
    image: couchbase/ubuntu
    hostname: 'node_two'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "9092:8091"
    container_name: ubuntu-node-two
    command: --version 7.0.2 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -r
    privileged: true
  nocluster:
    image: couchbase/ubuntu
    hostname: 'no_cluster'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "9093:8091"
    container_name: ubuntu-no-cluster
    command: --version 7.0.2 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -r --no-cluster --services data,index,query,analytics,eventing,fts -dm 256 -im 256 -qm 256 -am 1024 -em 256 -sm 256
    privileged: true    
  gateway:
    image: couchbase/ubuntu
    hostname: 'gateway'
    tty: true
    depends_on:
      - rallyhost
    networks:
      - cb-net-ubuntu
    ports: 
      - "9095:4985"
      - "9096:4984"
    container_name: gateway
    command: --version 2.8.2 -u couchbase -p foo123! -ch ubuntu-clusterhost -d -os UBUNTU -g -r
    privileged: true  
networks:
  cb-net-ubuntu: